"""add social handles

Revision ID: 32079445d8ec
Revises: 0007_google_oauth
Create Date: 2026-07-26 02:11:38.476809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32079445d8ec'
down_revision = '0007_google_oauth'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github_handle', sa.String(), nullable=True))
    op.add_column('users', sa.Column('linkedin_handle', sa.String(), nullable=True))
    op.add_column('users', sa.Column('huggingface_handle', sa.String(), nullable=True))
    op.add_column('users', sa.Column('kaggle_handle', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'kaggle_handle')
    op.drop_column('users', 'huggingface_handle')
    op.drop_column('users', 'linkedin_handle')
    op.drop_column('users', 'github_handle')
    # ### end Alembic commands ###