"""add_agent_release_fields

Revision ID: 6cf91349339e
Revises: c3b975bf3c53
Create Date: 2026-08-15 01:11:19.548972

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6cf91349339e'
down_revision = 'c3b975bf3c53'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_settings', sa.Column('agent_version', sa.String(), nullable=True))
    op.add_column('system_settings', sa.Column('agent_patch_notes', sa.String(), nullable=True))
    op.add_column('system_settings', sa.Column('agent_download_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_settings', 'agent_download_url')
    op.drop_column('system_settings', 'agent_patch_notes')
    op.drop_column('system_settings', 'agent_version')
    # ### end Alembic commands ###