"""job_cost_duration_remove_gdrive

Revision ID: f451283e1832
Revises: 0006_dataset_artifacts_gdrive
Create Date: 2026-07-16 21:09:57.820072

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f451283e1832'
down_revision = '0006_dataset_artifacts_gdrive'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notebook_sessions')
    op.add_column('jobs', sa.Column('duration_seconds', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('cost', sa.Float(), nullable=True))
    op.drop_column('jobs', 'gdrive_refresh_token_enc')
    op.drop_column('jobs', 'gdrive_file_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('gdrive_file_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('gdrive_refresh_token_enc', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('jobs', 'cost')
    op.drop_column('jobs', 'duration_seconds')
    op.create_table('notebook_sessions',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('gpu_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('starting', 'ready', 'busy', 'idle', 'dead', name='notebooksessionstatus'), autoincrement=False, nullable=False),
    sa.Column('notebook_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('oci_key', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('billed_seconds', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('last_active_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('ended_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], name='notebook_sessions_client_id_fkey'),
    sa.ForeignKeyConstraint(['gpu_id'], ['gpus.id'], name='notebook_sessions_gpu_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='notebook_sessions_pkey')
    )
    # ### end Alembic commands ###